version: 2
jobs:
  build:
    working_directory: ~/sdamksu-frontend
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - restore_cache:
          key: sdamksu-frontend-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: sdamksu-frontend-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
      - run: xvfb-run -a npm run test -- --no-watch --no-progress --browsers=ChromeNoSandbox
      # - run: xvfb-run -a npm run e2e -- --protractor-config=protractor-ci.conf.js